### ISSUE TITLE
Sourcing bash alias with question mark triggers `No matches for wildcard` error

### ISSUE THREAD

**Issue by LucasPickering** [edc/bass#87] opened 2020-06-24 13:25 UTC
I'm trying to source a bash script that defines the alias `k?`. Specifically it has this line:

```
alias k?='khelp;'
```

Sourcing this works just fine in bash, but when I source it via bass, I get:

```
No matches for wildcard 'k?='khelp;''. See `help expand`.
```

I can easily get around this by just commenting out that line in the script, but as this is a shared script for my company, I can't actually get rid of it. 

fish version: 3.1.2

Aside from this, bass has been great so far. Thank you!

**Comment by edc** [comment] 2020-07-20 04:11
The issue is that fish does not allow `?` in aliases:

```
$ alias k 'echo hello'
$ k
hello
$ alias k? 'echo hello'
fish: No matches for wildcard 'k?'. See `help expand`.
alias k? 'echo hello'
      ^
```

We could potentially replace the question mark in alias with something like `_`, but it might introduce conflict. Or we could also drop these problematic aliases. WDYT?

**Comment by LucasPickering** [comment] 2020-07-20 22:07
@edc I would suggest we just drop those aliases, but also print out a warning about it if possible so it doesn't happen invisible. I think that's probably the easiest and safest solution.

**Comment by edc** [comment] 2020-10-29 05:03
Thanks for reporting, and sorry about the late response. This is now fixed.

**Closed** 2020-10-29 05:03 UTC
